Component({
    properties:{
     visible:{
        type:Boolean,
        value:true
     },
     placeholder:{
       type:String,
       value:""
     }
    },
    data:{
      value:""
    },
    methods:{
      confirm(){
        this.triggerEvent('confirm',this.data.value)
      },
      cancel(){
        this.triggerEvent('cancel',this.data.value)
      },
      watchValue(event){
        this.data.value=event.detail.value;
        
      }
    }
})